on:
  workflow_dispatch:
  push:

jobs:
  dryrun:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: docker run --rm -v $PWD/aws-nuke.yaml:/config.yml
          quay.io/rebuy/aws-nuke:v2.25.0
          --config /config.yml --force --force-sleep 3 --quiet
          --access-key-id ${{ secrets.AWS_ACCESS_KEY_ID }} --secret-access-key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
