name: nuke-extended-time

on:
  schedule:
    - cron: "30 9 * * *"
  workflow_dispatch:

jobs:
  nuke:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker run --rm -v $PWD/aws-nuke-extended-time.yaml:/config.yml
          quay.io/rebuy/aws-nuke:v2.23.0
          --config /config.yml --force --force-sleep 3 --quiet --no-dry-run
          --access-key-id ${{ secrets.AWS_ACCESS_KEY_ID }} --secret-access-key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
